[package]
name = "gcs-indexer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
time = "0.3.44"
google-cloud-storage = { package="gcloud-storage", version="1.0.0" }
tokio = {version = "1.47.1", features = ["full"]}
warp = {version ="0.3.6"}
